import {Task} from "../../types/Task.ts";

const today = new Date();

const firstDayOfWeek = today.getDate() - today.getDay()
const lastDayOfWeek = today.getDate() - today.getDay() + 6

const firstDayOfNextWeek = today.getDate() - today.getDay() + 7
const lastDayOfNextWeek = today.getDate() - today.getDay() + 13

console.log(lastDayOfWeek)
console.log(firstDayOfNextWeek)
console.log(lastDayOfNextWeek)

export const mockTasks: Task[] = [
    {
        id: 1,
        user_id: 101,
        title: 'Task 1',
        description: 'Description for Task 1',
        total_task_time: 120,
        status: 'pending',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 2,
        user_id: 102,
        title: 'Task 2',
        description: 'Description for Task 2',
        total_task_time: 90,
        status: 'in_progress',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 3,
        user_id: 103,
        title: 'Task 3',
        description: 'Description for Task 3',
        total_task_time: 60,
        status: 'completed',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 4,
        user_id: 104,
        title: 'Task 4',
        description: 'Description for Task 4',
        total_task_time: 45,
        status: 'canceled',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 5,
        user_id: 105,
        title: 'Task 5',
        description: 'Description for Task 5',
        total_task_time: 150,
        status: 'pending',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 6,
        user_id: 106,
        title: 'Task 6',
        description: 'Description for Task 6',
        total_task_time: 30,
        status: 'in_progress',
        due_date: new Date(today.getFullYear(), today.getMonth(),  today.getDate()),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 7,
        user_id: 107,
        title: 'Task 7',
        description: 'Description for Task 7',
        total_task_time: 75,
        status: 'completed',
        due_date:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 8,
        user_id: 108,
        title: 'Task 8',
        description: 'Description for Task 8',
        total_task_time: 200,
        status: 'canceled',
        due_date:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 9,
        user_id: 109,
        title: 'Task 9',
        description: 'Description for Task 9',
        total_task_time: 110,
        status: 'pending',
        due_date: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), today.getDate()),
        completed_at: new Date(today.getFullYear(), today.getMonth(), today.getDate()),
    },
    {
        id: 10,
        user_id: 110,
        title: 'Task 10',
        description: 'Description for Task 10',
        total_task_time: 95,
        status: 'in_progress',
        due_date:  new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 11,
        user_id: 111,
        title: 'Task 11',
        description: 'Description for Task 11',
        total_task_time: 80,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 12,
        user_id: 112,
        title: 'Task 12',
        description: 'Description for Task 12',
        total_task_time: 140,
        status: 'completed',
        due_date: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 13,
        user_id: 113,
        title: 'Task 13',
        description: 'Description for Task 13',
        total_task_time: 50,
        status: 'in_progress',
        due_date: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 14,
        user_id: 114,
        title: 'Task 14',
        description: 'Description for Task 14',
        total_task_time: 100,
        status: 'canceled',
        due_date: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 15,
        user_id: 115,
        title: 'Task 15',
        description: 'Description for Task 15',
        total_task_time: 60,
        status: 'pending',
        due_date: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        assigned_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfWeek),
    },
    {
        id: 16,
        user_id: 116,
        title: 'Task 16',
        description: 'Description for Task 16',
        total_task_time: 130,
        status: 'completed',
        due_date: new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        completed_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
    },
    {
        id: 17,
        user_id: 117,
        title: 'Task 17',
        description: 'Description for Task 17',
        total_task_time: 70,
        status: 'in_progress',
        due_date:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
    },
    {
        id: 19,
        user_id: 119,
        title: 'Task 19',
        description: 'Description for Task 19',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
    },
    {
        id: 20,
        user_id: 120,
        title: 'Task 20',
        description: 'Description for Task 20',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), firstDayOfNextWeek),
    },
    {
        id: 21,
        user_id: 121,
        title: 'Task 21',
        description: 'Description for Task 21',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
    },
    {
        id: 22,
        user_id: 122,
        title: 'Task 22',
        description: 'Description for Task 22',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
    },
    {
        id: 23,
        user_id: 123,
        title: 'Task 23',
        description: 'Description for Task 23',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
    },
    {
        id: 24,
        user_id: 124,
        title: 'Task 24',
        description: 'Description for Task 24',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
    },
    {
        id: 25,
        user_id: 125,
        title: 'Task 25',
        description: 'Description for Task 25',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        assigned_at:  new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
        completed_at: new Date(today.getFullYear(), today.getMonth(), lastDayOfNextWeek),
    },
    {
        id: 26,
        user_id: 126,
        title: 'Task 26',
        description: 'Description for Task 26',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth() + 1, 1),
        assigned_at:  new Date(today.getFullYear(), today.getMonth() + 1, 1),
        completed_at: new Date(today.getFullYear(), today.getMonth()+ 1, 1),
    },
    {
        id: 27,
        user_id: 127,
        title: 'Task 27',
        description: 'Description for Task 27',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth() + 1, 1),
        assigned_at:  new Date(today.getFullYear(), today.getMonth() + 1, 1),
        completed_at: new Date(today.getFullYear(), today.getMonth() + 1, 1),
    },
    {
        id: 28,
        user_id: 128,
        title: 'Task 28',
        description: 'Description for Task 28',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth() + 2, 1),
        assigned_at:  new Date(today.getFullYear(), today.getMonth() + 2, 1),
        completed_at: new Date(today.getFullYear(), today.getMonth() + 2, 1),
    },
    {
        id: 29,
        user_id: 129,
        title: 'Task 29',
        description: 'Description for Task 29',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth() + 2, 1),
        assigned_at:  new Date(today.getFullYear(), today.getMonth() + 2, 1),
        completed_at: new Date(today.getFullYear(), today.getMonth() + 2, 1),
    },
    {
        id: 30,
        user_id: 130,
        title: 'Task 30',
        description: 'Description for Task 30',
        total_task_time: 90,
        status: 'pending',
        due_date:  new Date(today.getFullYear(), today.getMonth() + 2, 1),
        assigned_at:  new Date(today.getFullYear(), today.getMonth()+ 2, 1),
        completed_at: new Date(today.getFullYear(), today.getMonth()+ 2, 1),
    }
]